name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate contribution snake
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: bittusharma3
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit and push snake
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate contribution snake"
          add: "dist"
